apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default "hello-openshift" }}
  namespace: {{ .Values.namespace | default "crc-local" }}
  labels:
    app: {{ .Values.name | default "hello-openshift" }}
spec:
  selector:
    app: {{ .Values.name | default "hello-openshift" }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
